name: "Validate PR Title"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
permissions:
  pull-requests: write
  statuses: write
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
          types: |
            feature
            fix
            documentation
